services:
  kademliaNodes:
    image: kadlab:latest # Make sure your Docker image has this name.
    stdin_open: true
    tty: true
    env_file: ./.env
    deploy:
      mode: replicated
      replicas: ${NUMBER_OF_REPLICAS}
      # resources:
      #   limits:
      #      cpus: "0.1"
      #      memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    # expose:
    #   - 8000  

    networks:
      - kademlia_network
      
networks:
  kademlia_network:

