services:
  bootstrapNode:
    image: kadlab:latest # Make sure your Docker image has this name.
    stdin_open: true
    tty: true
    env_file: ./.env
    command:
      [
        "/app/main",
        "start",
        "--bootstrap",
        "1234567890abcdef1234567890abcdef12345678",
        "-v",
      ]
    deploy:
      mode: replicated
      replicas: 1
      # resources:
      #   limits:
      #      cpus: "0.1"
      #      memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s

    networks:
      - kademlia_network

  kademliaNodes:
    image: kadlab:latest # Make sure your Docker image has this name.
    stdin_open: true
    tty: true
    env_file: ./.env
    command:
      [
        "/app/main",
        "start",
        "--join-id",
        "1234567890abcdef1234567890abcdef12345672",
        "-v",
      ]
    deploy:
      mode: replicated
      replicas: ${NUMBER_OF_REPLICAS}
      # resources:
      #   limits:
      #      cpus: "0.1"
      #      memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    # expose:
    #   - 8000

    networks:
      - kademlia_network

networks:
  kademlia_network:
