name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Label of the container job
  runner-job:
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'labs/go.mod'
          cache-dependency-path: |
             labs/go.sum

      - name: Build
        run: go build ./labs/...

      - name: Test
        run: go test ./labs/...
        env:
          TZ: Europe/Stockholm
